export { default as Navbar } from "./nav/Navbar"
export { default as BlackBackground } from "./black-background/BlackBackground"
export { default as Register } from "./register/Register"
export { default as Moduls_slider } from "./moduls-slider/Moduls_slider"
export { default as CertificateStages } from "./certificate-stages/CertificateStages"
export { default as Partners } from "./partners/Partners"
export { default as Footer } from "./footer/Footer"
